In [2]:
import numpy as np

In [10]:
# 1-D array

arr1d = np.array([1,2,3,4,5])
print(arr1d)
type(arr1d)

[1 2 3 4 5]


numpy.ndarray

In [4]:
# 2-D array

arr2d = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [5]:
# 3-D array

arr3d = np.array([[[1,2,3,4,5],[6,7,8,9,10]],
                  [[11,12,13,14,15],[16,17,18,19,20]]])
print(arr3d)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [7]:
# dimension of the array - ndim

print(arr1d.ndim)
print(arr2d.ndim)
print(arr3d.ndim)

1
2
3


In [11]:
# accessing the element of the array

print(arr1d[4])

print(arr2d[0][4])
# print(arr2d[0, 4])

print(arr3d[0][0][4])
# print(arr3d[0, 0, 4])

5
5
5


In [14]:
# slicing

print(arr1d[1:4])

print(arr2d[0][1:4])
# print(arr2d[0, 1:4])

print(arr3d[0][0][1:4])
# print(arr3d[0, 0, 1:4])

[2 3 4]
[2 3 4]
[2 3 4]


In [15]:
# shape of the array

print(arr1d.shape)
print(arr2d.shape)
print(arr3d.shape)

(5,)
(2, 5)
(2, 2, 5)


In [17]:
# reshaping

print('Original Array')
print(arr2d)

print('Reshaped Array')
print(arr2d.reshape([5,2]))

Original Array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Reshaped Array
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [19]:
# arange(start, stop, step)

a = np.arange(1,10,2)
print(a)

b = np.arange(25)
b = b.reshape([5,5])
print(b)

[1 3 5 7 9]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [21]:
for i in a:
    print(i, end=' ')

print('')
for i in b:
    for j in i:
        print(j, end=' ')

1 3 5 7 9 
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 

In [22]:
# nditer

for i in np.nditer(b):
    print(i, end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 

In [23]:
# concatenate

a1 = np.arange(10,40,10)
a2 = np.arange(40,70, 10)

np.concatenate([a1, a2])

array([10, 20, 30, 40, 50, 60])

In [27]:
# use of axis parameter

a1 = np.array([[1,2,3], [4,5,6]])
a2 = np.array([[1,2,3], [4,5,6]])

np.concatenate((a1, a2), axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [31]:
# searching - np.where()

a = np.arange(10,60,10)
print(np.where(a == 40))

print(np.where(a % 20 == 0))

(array([3]),)
(array([1, 3]),)


In [32]:
# sorting - np.sort()

a = np.array([4,2,5,3,1])
print(np.sort(a))

[1 2 3 4 5]


In [37]:
# shuffle and permutation

# shuffle changes the original array
a1 = np.arange(10)
np.random.shuffle(a1)
print(a1)

# permutation preserves the original array
a2 = np.arange(10)
print(np.random.permutation(a2))

[2 3 4 9 7 0 1 8 6 5]
[5 8 2 6 9 4 7 1 3 0]


In [57]:
# matrix operations

mat1 = np.array([[1,2,3],[4,5,6], [7,8,9]])
mat2 = np.array([[1,2,3],[4,5,6], [7,8,9]])

#addition
print(mat1 + mat2)
# print(np.add(mat1, mat2))

#substraction
print(mat1 - mat2)
# print(np.subtract(mat1, mat2))

# scalar multiplication
print(mat1 * mat2)
# print(np.multiply(mat1, mat2))

# division
print(mat1 / mat2)
# print(np.divide(mat1, mat2))

# dot product
print(np.dot(mat1, mat2))

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [43]:
# minimum value and the maximum value

print(np.min(mat1))
print(np.max(mat1))

1
6


In [46]:
# diagonal of matrix

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.diagonal(a)

array([1, 5, 9])

In [48]:
# transpose the matrix

print(a.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [51]:
# rotate the matrix - rot90()

print(np.rot90(a))

[[3 6 9]
 [2 5 8]
 [1 4 7]]


In [53]:
# sum of diagonal - trace

print(np.trace(a))
# print(a.trace())

15


In [55]:
# stats functions

print(np.mean(a)) # mean
print(np.median(a)) # median
print(np.var(a)) # variance
print(np.std(a)) # standard deviation

5.0
5.0
6.666666666666667
2.581988897471611


In [58]:
# absolute value

a = np.array([1,-1,2,-2])
print(np.absolute(a))

[1 1 2 2]


In [62]:
# rounding

a = np.array([1.22112211, 4.313211])
print(np.trunc(a))
print(np.around(a,2))
print(np.floor(a))
print(np.ceil(a))

[1. 4.]
[1.22 4.31]
[1. 4.]
[2. 5.]


In [4]:
# summation and product

a = np.arange(5)

print(np.sum(a))
print(np.product(a))

10
0


In [5]:
# unique values of the array

a = np.array([1,2,3,2,1])
np.unique(a)

array([1, 2, 3])

In [9]:
# union and intersection from array

a1 = np.array([10,20,30])
a2 = np.array([20,40,60])
print(np.union1d(a1,a2))
print(np.intersect1d(a1,a2))

[10 20 30 40 60]
[20]


In [15]:
# additional array operations

# matrix with 0 values
z = np.zeros((2,2))
print(z)

# matrix with 1 values
o = np.ones((2,2))
print(o)

# matrix with some constant value
f = np.full((2,2),5)
print(f)

# identity matrix
i = np.eye(2,2)
print(i)

# random matrix between 0 and 1
r = np.random.random((2,2))
print(r)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[5 5]
 [5 5]]
[[1. 0.]
 [0. 1.]]
[[0.0714197  0.22998765]
 [0.8787404  0.78324774]]
